baseurl = "https://5f6fb5a2b444f52da2be16a1--jovial-liskov-b176a1.netlify.app/"
languageCode = "en-us"
languageLang = "en"
title = "Kathy Smith | Photography"
theme = "beautifulhugo"
paginate = 999

[Params]
  subtitle = "Build a beautiful and simple website in minutes"
  mainSections = ["post","posts"]
  logo = "android-chrome-144x144" # Expecting square dimensions
  favicon = "favicon.ico"
  dateFormat = "January 2, 2006"
  socialShare = false
  copyrightDate = "2020"
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"


[Author]
name = "Kathy Smith"
website = "https://kathysmith.photography/"
# facebook = "kathy.smith.33046"

[menu]
  [[menu.main]]
      name = "Action"
      identifier = "action"
      url = "/categories/action"
      weight = 1

  [[menu.main]]
      parent = "action"
      name = "Sports"
      url = "/categories/sports"
      weight = 1

  [[menu.main]]
      parent = "action"
      name = "Events"
      url = "/categories/events"
      weight = 2

  [[menu.main]]
      parent = "action"
      name = "Motion"
      url = "/categories/motion"
      weight = 3

  [[menu.main]]
      identifier = "people"
      url = "/categories/people"
      name = "People"
      weight = 1

  [[menu.main]]
      parent = "people"
      name = "Black and White"
      url = "/categories/bw"
      weight = 1

  [[menu.main]]
      parent = "people"
      name = "Color"
      url = "/categories/color"
      weight = 1
      
   [[menu.main]]
      parent = "people"
      name = "Street"
      url = "/categories/street"
      weight = 1     

  [[menu.main]]
      identifier = "scapes"
      name = "Scapes"
      url = "/categories/scapes"
      weight = 1

  [[menu.main]]
      identifier = "stills"
      name = "Stills"
      url = "/categories/stills"
      weight = 1

  [[menu.main]]
      identifier = "wild"
      url = "/categories/wild"
      name = "Wild"
      weight = 1

  [[menu.main]]
      parent = "wild"
      url = "/categories/birds"
      name = "Birds"
      weight = 1

  [[menu.main]]
      parent = "wild"
      url = "/categories/pets"
      name = "Pets"
      weight = 1

  [[menu.main]]
      parent = "wild"
      url = "/categories/zoo"
      name = "Zoo"
      weight = 1

  [[menu.main]]
      parent = "stills"
      url = "/categories/abstracts"
      name = "Abstracts"
      weight = 1

  [[menu.main]]
      parent = "stills"
      url = "/categories/flowers"
      name = "Flowers"
      weight = 1

  [[menu.main]]
      parent = "stills"
      url = "/categories/studio"
      name = "Studio"
      weight = 1

  [[menu.main]]
      parent = "scapes"
      url = "/categories/land"
      name = "Land"
      weight = 1

  [[menu.main]]
      parent = "scapes"
      url = "/categories/sea"
      name = "Sea"
      weight = 1

  [[menu.main]]
      parent = "scapes"
      url = "/categories/city"
      name = "City"
      weight = 1
